### ISSUE TITLE
Can't open file / Some CMake errors

### ISSUE THREAD

**Issue by mr-cheffy** [jgarciapueyo/stoc#3]
## Can't open file

When I try to open a *.st file, I get a file not found and I saw in your source code that I are checking for `\` to separate the path and that will not work on Linux
![Screenshot_20220825_140519](https://user-images.githubusercontent.com/91018726/186659725-12da6c0e-d308-4496-938f-81d5be03b358.png)
.

## Some CMake errors

I got some errors trying to build your programming language, I fixed it by changing CMakeLists.txt[40] to `target_link_libraries(stoc ${llvm_libs})` and removed on subdirectory that didn't exist (`utils/llvm-bitcode-examples`)

**Comment by jgarciapueyo** [comment]
Thank you for trying to compile and execute the stoc compiler and the feedback! Unfortunately this was a university project and I am no longer maintaining it so I will close the issue right now. If you need any other thing, do not hesitate to contact me and I'll try to help.
